# .github/workflows/build.yml
name: Build Package

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: aynrand

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build package
      run: make build

    - name: Verify bytecode
      run: make verify

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: move-package
        path: build/